version: '3.3'

services:
  frontend-node:
    image: node:20-alpine3.19
    volumes:
      - .:/var/www
      - /var/www/node_modules
    working_dir: /var/www
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"
    ports:
      - '5173:5173'

  frontend-static:
    image: node:20-alpine3.19
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: sh -c "yarn install && yarn build && npx http-server dist -p 80"
    ports:
      - '80:80'